2020-04-24 06:38:34,149 - ERROR : server	no_id	Traceback (most recent call last):
  File "server.py", line 87, in get
    data_dict = json.loads(self.request.body)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2020-04-24 06:38:53,109 - ERROR : server	no_id	Traceback (most recent call last):
  File "server.py", line 87, in get
    data_dict = json.loads(self.request.body)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2020-04-24 06:40:10,630 - ERROR : server	no_id	Traceback (most recent call last):
  File "server.py", line 87, in get
    data_dict = json.loads(self.request.body)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2020-04-24 06:40:22,019 - ERROR : server	no_id	Traceback (most recent call last):
  File "server.py", line 87, in get
    data_dict = json.loads(self.request.body)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2020-04-24 06:45:33,461 - ERROR : server	"123"	Traceback (most recent call last):
  File "server.py", line 89, in get
    title = self.get_argument('title')
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/site-packages/tornado/web.py", line 455, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/site-packages/tornado/web.py", line 538, in _get_argument
    raise MissingArgumentError(name)
tornado.web.MissingArgumentError: HTTP 400: Bad Request (Missing argument title)

2020-04-24 06:46:30,905 - ERROR : server	"123"	Traceback (most recent call last):
  File "server.py", line 92, in get
    url = self.get_argument('url')
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/site-packages/tornado/web.py", line 455, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "/home/services/zhaozhenyu/conda3/lib/python3.7/site-packages/tornado/web.py", line 538, in _get_argument
    raise MissingArgumentError(name)
tornado.web.MissingArgumentError: HTTP 400: Bad Request (Missing argument url)

